language: go

# need sudo as long as ubuntu has old libgit2 versions
sudo: required
dist: trusty

# install libgit2
before_install:
    - cd "${HOME}"
    - wget -O libgit2.tar.gz https://github.com/libgit2/libgit2/archive/v0.23.1.tar.gz
    - tar -xzvf libgit2.tar.gz
    - cd libgit2-0.23.1 && mkdir build && cd build
    - cmake -DTHREADSAFE=ON -DBUILD_CLAR=OFF -DCMAKE_BUILD_TYPE="RelWithDebInfo" .. && make && sudo make install
    - sudo ldconfig
    - cd "${TRAVIS_BUILD_DIR}"

# install go dependencies
install: make deps

# travis automatically runs 'go test' for us
